name: windows-build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: choco installing
        run: |
          choco install cmake -y
          choco install llvm -y

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install sccache
        run: cargo install sccache

      - name: Build
        run: cargo build
